-- ============================================================================
--  Two-tier public trust for attribution
-- ----------------------------------------------------------------------------
--  A hearing can reach two publicly-distinct trust levels:
--    * attributed — speaker identities generated by the LLM and ACCEPTED by a
--                   human in a fast pass. Publicly readable, labeled AI-assisted,
--                   fully revisable. This is how coverage scales.
--    * verified   — a human has carefully reviewed the hearing (eventually
--                   including the text/grammar pass). The weightier claim.
--
--  hearings.status is the SINGLE source of truth for the public tier label
--  (attributed vs verified) — the label is never derived from turn aggregates.
--  speaker_turns.attribution_status tracks the per-turn review workflow.
--
--  Both CHECK extensions are additive (existing values, incl. legacy 'published',
--  are preserved). 'verified' at the turn level is RESERVED for future per-turn
--  human confirmation (the text slice) and is not written by the attribution flow.
-- ============================================================================

ALTER TABLE hearings DROP CONSTRAINT IF EXISTS hearings_status_check;
ALTER TABLE hearings ADD  CONSTRAINT hearings_status_check
    CHECK (status IN ('scheduled','live','processing','published','transcribing','draft','attributed','verified'));

ALTER TABLE speaker_turns DROP CONSTRAINT IF EXISTS speaker_turns_attribution_status_check;
ALTER TABLE speaker_turns ADD  CONSTRAINT speaker_turns_attribution_status_check
    CHECK (attribution_status IN ('auto','verified','unverified','edited','attributed'));

-- One-time honesty normalization: every existing 'verified' turn was accepted via
-- the OLD one-click flow — a tier-1 AI-assisted acceptance, NOT a careful human
-- verification. Relabel to 'attributed' so the trust tier is truthful. This runs
-- exactly once (migrate.js records applied files in schema_migrations), so future
-- genuine per-turn 'verified' set by the text slice is never touched.
UPDATE speaker_turns SET attribution_status = 'attributed' WHERE attribution_status = 'verified';
