// Public-facing trust tier labels, driven solely by hearings.status.
// Kept in one place so the card badge, the transcript header badge, and the
// transcript banner all say the same honest thing.

export type TierKey = 'draft' | 'attributed' | 'verified'

// Compact badge (hearing cards, header chip). Prominent, not a subtle grey —
// a reader should know the trust level at a glance.
export const TIER_BADGE: Record<string, { label: string; cls: string }> = {
  draft:      { label: 'Draft',          cls: 'bg-amber-100 text-amber-800 border border-amber-300' },
  attributed: { label: 'AI-attributed',  cls: 'bg-blue-100 text-blue-800 border border-blue-300' },
  verified:   { label: 'Human-verified', cls: 'bg-green-100 text-green-800 border border-green-300' },
  // operational states (kept for completeness)
  scheduled:  { label: 'Scheduled',   cls: 'bg-yellow-100 text-yellow-700' },
  live:       { label: 'Live',        cls: 'bg-green-100 text-green-700' },
  processing: { label: 'Processing',  cls: 'bg-blue-100 text-blue-700' },
  transcribing: { label: 'Transcribing', cls: 'bg-blue-100 text-blue-700' },
  published:  { label: 'Published',   cls: 'bg-slate-100 text-slate-600' },
}

export function tierBadge(status: string) {
  return TIER_BADGE[status] ?? { label: status, cls: 'bg-slate-100 text-slate-600' }
}

// Prominent full-width banner on the transcript page — the reader-facing trust
// signal that sits above the quotes.
export const TIER_BANNER: Record<TierKey, { title: string; body: string; cls: string; icon: string }> = {
  draft: {
    icon: '⚠️',
    title: 'Draft transcript',
    body: 'Speakers are auto-diarized from the audio and not yet attributed to members — the labels below (“Speaker 1”, “Speaker 2”…) are raw diarization output.',
    cls: 'bg-amber-50 border-amber-300 text-amber-900',
  },
  attributed: {
    icon: '🤖',
    title: 'Speakers attributed — AI-assisted',
    body: 'Speaker identities were generated by AI and accepted by a human reviewer. They have not yet been carefully human-verified and may be revised.',
    cls: 'bg-blue-50 border-blue-300 text-blue-900',
  },
  verified: {
    icon: '✓',
    title: 'Human-verified',
    body: 'A person has reviewed the speaker attributions on this transcript.',
    cls: 'bg-green-50 border-green-300 text-green-900',
  },
}

export function tierBanner(status: string): { title: string; body: string; cls: string; icon: string } | null {
  return (status in TIER_BANNER) ? TIER_BANNER[status as TierKey] : null
}
